batch_size: 32
bidirectional: true
class_weights:
- 1.0
- 3.0
dropout: 0.75
gradient_clip_val: 1
learning_rate: 0.0001
n_classes: 2
n_epochs: 3
n_features: 13
n_hidden: 100
n_layers: 2
weight_decay: 1.0e-05
